### ISSUE TITLE
No releases available

### ISSUE THREAD

**Issue by pataquets** [tom-on-the-internet/binary-clock#2]
As instructed by readme, browsed to releases via the included link.
Release list is empty (but `.goreleaser.yaml` file is present on repo).
Not familiar enough with Golang to review neithe the Github Action pipeline, nor `.goreleaser.yaml` file.

**Comment by tom-on-the-internet** [comment]
Hello Alfonso!

Thanks for reaching out. I haven't played around this project in quite a while.
I have created the releases. Sorry for the confusion.

I'm curious what you are using this for. It was fun to play around with a couple years ago. I might use it again someday.
